#!/bin/bash

# Example usage:
# meme "This is an example meme test" ~/.meme_images/dank-meme.png

TMP="/tmp/temp.png"
TMP_OUT="/tmp/output.png"

rm $TMP &> /dev/null
rm $TMP_OUT &> /dev/null

label=$1

# Override filename with `randomFilename` and the parameter being the directory
# of the images to randomize
filename=$2

if [ -z "$filename" ]; then
  echo "No filename provided, exiting"
  exit 0
fi

#
# Edit text size and stroke width here!
#

params="-pointsize 42 -stroke black -strokewidth 2 -fill white -font \"VerdanaB\" -gravity North"

# Takes parameter of a directory with images
randomFilename() {
  RANDOM_DIR=$1
  fileList=()
  for x in `find $RANDOM_DIR -type f`; do
    fileList+=($x)
  done

  number=${#fileList[@]}
  randomNumber=$(($RANDOM % $number))
  filename=${fileList[$randomNumber]}
}

ident=$(identify -format "%wx%h" $filename)
size_w=$(echo $ident |cut -d"x" -f1)
size_y=$(echo $ident |cut -d"x" -f2)
size="$size_w"x"$size_h"

cmd="convert -background transparent -size $size $params caption:'$label' $TMP"
eval $cmd

output_cmd="convert $filename $TMP -size $size -composite $TMP_OUT"
eval $output_cmd

echo "File output: $TMP_OUT"
